-- Roles
CREATE TABLE roles (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50)  NOT NULL UNIQUE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Departments
CREATE TABLE departments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100) NOT NULL,
    monthly_budget  NUMERIC(12,2),
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Users
CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           VARCHAR(255) NOT NULL UNIQUE,
    password_hash   VARCHAR(255) NOT NULL,
    role_id         BIGINT       NOT NULL REFERENCES roles(id),
    department_id   BIGINT       REFERENCES departments(id),
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_user_email      ON users(email);
CREATE INDEX idx_user_role       ON users(role_id);
CREATE INDEX idx_user_department ON users(department_id);

-- Expense reports
CREATE TABLE expense_reports (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL REFERENCES users(id),
    status          VARCHAR(20)  NOT NULL,
    total_amount    NUMERIC(12,2) NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_report_user    ON expense_reports(user_id);
CREATE INDEX idx_report_status  ON expense_reports(status);
CREATE INDEX idx_report_created ON expense_reports(created_at);

-- Expense items
CREATE TABLE expense_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id   BIGINT       NOT NULL REFERENCES expense_reports(id),
    category    VARCHAR(50)  NOT NULL,
    amount      NUMERIC(12,2) NOT NULL,
    description VARCHAR(500),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_item_report ON expense_items(report_id);

-- Approvals
CREATE TABLE approvals (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id   BIGINT       NOT NULL REFERENCES expense_reports(id),
    manager_id  BIGINT       NOT NULL REFERENCES users(id),
    decision    VARCHAR(20)  NOT NULL,
    decided_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_approval_report  ON approvals(report_id);
CREATE INDEX idx_approval_manager ON approvals(manager_id);

-- Audit logs
CREATE TABLE audit_logs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action          VARCHAR(100) NOT NULL,
    performed_by    BIGINT       REFERENCES users(id),
    timestamp       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_audit_performed_by ON audit_logs(performed_by);
CREATE INDEX idx_audit_timestamp    ON audit_logs(timestamp);
